In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance.csv')
dataset

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,False,True,False,False,True
1,18,33.770,1,1725.55230,True,False,False,True,False
2,28,33.000,3,4449.46200,True,False,False,True,False
3,33,22.705,0,21984.47061,True,False,True,False,False
4,32,28.880,0,3866.85520,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,True,False,True,False,False
1334,18,31.920,0,2205.98080,False,False,False,False,False
1335,18,36.850,0,1629.83350,False,False,False,True,False
1336,21,25.800,0,2007.94500,False,False,False,False,True
1337,61,29.070,0,29141.36030,False,True,True,False,False

In [4]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes','region_northwest','region_southeast','region_southwest']]
dep=dataset['charges']

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [18]:
from sklearn.ensemble import AdaBoostRegressor
# regr = AdaBoostRegressor(random_state=0, n_estimators=100)
# regr.fit(X, y)
from sklearn.model_selection import GridSearchCV
param_grid = {'estimator':[None,'object'],
              'learning_rate': [1.0, 1.5, 2.0,2.5],
'random_state': [None, 0, 10, 100, 1000]}

In [19]:
grid = GridSearchCV(AdaBoostRegressor(), param_grid, refit = True, verbose=3,n_jobs=-1)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:489: FitFailedWarning:
100 fits failed out of a total of 200.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
100 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'estimator' parameter of AdaBoostRegressor must be an object implementing 'fit' and 'predict' or None. Got 'object' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1234: UserWarning: One or more of the test scores are non-finite: [0.78567217 0.80113041 0.79401129 0.77405238 0.77803465 0.8140245
 0.79969651 0.81776279 0.75908977 0.80038464 0.81673832 0.73711285
 0.7999355  0.67793037 0.81714151 0.73194769 0.68913502 0.74187167
 0.71046615 0.76269544        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan]
  warnings.warn(

GridSearchCV(estimator=AdaBoostRegressor(), n_jobs=-1,
             param_grid={'estimator': [None, 'object'],
                         'learning_rate': [1.0, 1.5, 2.0, 2.5],
                         'random_state': [None, 0, 10, 100, 1000]},
             verbose=3)

In [20]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'estimator': None, 'learning_rate': 1.5, 'random_state': 10}:

In [21]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_estimator,param_learning_rate,param_random_state,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.224161,0.020407,0.014243,0.002104,NaN,1.0,None,"{'estimator': None, 'learning_rate': 1.0, 'ran...",0.750347,0.748881,0.805202,0.846489,0.777442,0.785672,0.036740,10
1,0.178135,0.047157,0.012937,0.003001,NaN,1.0,0,"{'estimator': None, 'learning_rate': 1.0, 'ran...",0.782168,0.776561,0.840682,0.825268,0.780973,0.801130,0.026520,5
2,0.114914,0.022890,0.013518,0.003441,NaN,1.0,10,"{'estimator': None, 'learning_rate': 1.0, 'ran...",0.777396,0.767066,0.825690,0.824411,0.775494,0.794011,0.025584,9
3,0.122260,0.031046,0.011801,0.002789,NaN,1.0,100,"{'estimator': None, 'learning_rate': 1.0, 'ran...",0.732716,0.721227,0.810180,0.819866,0.786272,0.774052,0.040131,12
4,0.136466,0.032924,0.014022,0.000998,NaN,1.0,1000,"{'estimator': None, 'learning_rate': 1.0, 'ran...",0.724562,0.756718,0.816823,0.801184,0.790886,0.778035,0.033224,11
5,0.075024,0.039145,0.009654,0.003092,NaN,1.5,None,"{'estimator': None, 'learning_rate': 1.5, 'ran...",0.807043,0.802516,0.859858,0.840934,0.759771,0.814024,0.034495,4
6,0.071948,0.009395,0.010435,0.001933,NaN,1.5,0,"{'estimator': None, 'learning_rate': 1.5, 'ran...",0.800597,0.722891,0.854884,0.825574,0.794536,0.799697,0.043913,8
7,0.098294,0.010405,0.011416,0.004381,NaN,1.5,10,"{'estimator': None, 'learning_rate': 1.5, 'ran...",0.793575,0.794050,0.854130,0.849438,0.797620,0.817763,0.027853,1
8,0.094281,0.024087,0.010280,0.002809,NaN,1.5,100,"{'estimator': None, 'learning_rate': 1.5, 'ran...",0.645912,0.726616,0.816279,0.822742,0.783901,0.759090,0.066033,14
9,0.066171,0.010760,0.007399,0.002208,NaN,1.5,1000,"{'estimator': None, 'learning_rate': 1.5, 'ran...",0.806299,0.740841,0.855435,0.815170,0.784178,0.800385,0.037662,6
10,0.085999,0.029173,0.010374,0.001403,NaN,2.0,None,"{'estimator': None, 'learning_rate': 2.0, 'ran...",0.817175,0.801775,0.865937,0.829916,0.768888,0.816738,0.031962,3
11,0.121853,0.040986,0.012944,0.003571,NaN,2.0,0,"{'estimator': None, 'learning_rate': 2.0, 'ran...",0.800597,0.603071,0.690034,0.825574,0.766288,0.737113,0.081105,16
12,0.074923,0.014952,0.009410,0.001097,NaN,2.0,10,"{'estimator': None, 'learning_rate': 2.0, 'ran...",0.704740,0.794050,0.854130,0.849438,0.797319,0.799935,0.053835,7
13,0.118028,0.060711,0.010934,0.003428,NaN,2.0,100,"{'estimator': None, 'learning_rate': 2.0, 'ran...",0.490875,0.607878,0.677385,0.822742,0.790772,0.677930,0.121327,20
14,0.064664,0.025869,0.007548,0.002461,NaN,2.0,1000,"{'estimator': None, 'learning_rate': 2.0, 'ran...",0.806299,0.800620,0.855435,0.839175,0.784178,0.817142,0.026187,2
15,0.106015,0.049646,0.011427,0.003151,NaN,2.5,None,"{'estimator': None, 'learning_rate': 2.5, 'ran...",0.604595,0.614525,0.857811,0.838177,0.744631,0.731948,0.107046,17
16,0.089666,0.022725,0.011194,0.002085,NaN,2.5,0,"{'estimator': None, 'learning_rate': 2.5, 'ran...",0.486209,0.653067,0.686289,0.825574,0.794536,0.689135,0.120177,19
17,0.079894,0.013772,0.008653,0.002274,NaN,2.5,10,"{'estimator': None, 'learning_rate': 2.5, 'ran...",0.544155,0.664316,0.854130,0.849438,0.797319,0.741872,0.120294,15
18,0.096227,0.022352,0.010215,0.002297,NaN,2.5,100,"{'estimator': None, 'learning_rate': 2.5, 'ran...",0.557291,0.791279,0.765766,0.647223,0.790772,0.710466,0.093274,18
19,0.089940,0.012920,0.009547,0.000664,NaN,2.5,1000,"{'estimator': None, 'learning_rate': 2.5, 'ran...",0.806299,0.607753,0.855435,0.839175,0.704816,0.762695,0.093497,13
20,0.003112,0.001358,0.000000,0.000000,object,1.0,None,"{'estimator': 'object', 'learning_rate': 1.0, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
21,0.002766,0.000493,0.000000,0.000000,object,1.0,0,"{'estimator': 'object', 'learning_rate': 1.0, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
22,0.002470,0.000370,0.000000,0.000000,object,1.0,10,"{'estimator': 'object', 'learning_rate': 1.0, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
23,0.001975,0.000269,0.000000,0.000000,object,1.0,100,"{'estimator': 'object', 'learning_rate': 1.0, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
24,0.002335,0.000424,0.000000,0.000000,object,1.0,1000,"{'estimator': 'object', 'learning_rate': 1.0, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
25,0.002641,0.000713,0.000000,0.000000,object,1.5,None,"{'estimator': 'object', 'learning_rate': 1.5, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
26,0.002075,0.000256,0.000000,0.000000,object,1.5,0,"{'estimator': 'object', 'learning_rate': 1.5, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
27,0.002113,0.000149,0.000000,0.000000,object,1.5,10,"{'estimator': 'object', 'learning_rate': 1.5, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
28,0.002142,0.000376,0.000000,0.000000,object,1.5,100,"{'estimator': 'object', 'learning_rate': 1.5, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
29,0.002559,0.000554,0.000000,0.000000,object,1.5,1000,"{'estimator': 'object', 'learning_rate': 1.5, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
30,0.002404,0.000338,0.000000,0.000000,object,2.0,None,"{'estimator': 'object', 'learning_rate': 2.0, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
31,0.001944,0.000106,0.000000,0.000000,object,2.0,0,"{'estimator': 'object', 'learning_rate': 2.0, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
32,0.002035,0.000209,0.000000,0.000000,object,2.0,10,"{'estimator': 'object', 'learning_rate': 2.0, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
33,0.001941,0.000313,0.000000,0.000000,object,2.0,100,"{'estimator': 'object', 'learning_rate': 2.0, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
34,0.002320,0.000174,0.000000,0.000000,object,2.0,1000,"{'estimator': 'object', 'learning_rate': 2.0, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
35,0.002300,0.000441,0.000000,0.000000,object,2.5,None,"{'estimator': 'object', 'learning_rate': 2.5, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
36,0.002066,0.000444,0.000000,0.000000,object,2.5,0,"{'estimator': 'object', 'learning_rate': 2.5, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
37,0.001779,0.000283,0.000000,0.000000,object,2.5,10,"{'estimator': 'object', 'learning_rate': 2.5, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
38,0.001766,0.000178,0.000000,0.000000,object,2.5,100,"{'estimator': 'object', 'learning_rate': 2.5, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21
39,0.001815,0.000267,0.000000,0.000000,object,2.5,1000,"{'estimator': 'object', 'learning_rate': 2.5, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,21